//id,url,longname,shortname
var gt = [
    [1,"FSB/01.html","Första Moseboken","1 Mos"],
    [2,"FSB/02.html","Andra Moseboken","2 Mos"],
    [3,"FSB/03.html","Tredje Moseboken","3 Mos"],
    [4,"FSB/04.html","Fjärde Moseboken","4 Mos"],
    [5,"FSB/05.html","Femte Moseboken","5 Mos"],
    [6,"FSB/06.html","Josua","Jos"],
    [7,"FSB/07.html","Domarboken","Dom"],
    [8,"FSB/08.html","Rut","Rut"],
    [9,"FSB/09.html","Första Samuelsboken","1 Sam"],
    [10,"FSB/10.html","Andra Samuelsboken","2 Sam"],
    [11,"FSB/11.html","Första Kungaboken","1 Kung"],
    [12,"FSB/12.html","Andra Kungaboken","2 Kung"],
    [13,"FSB/13.html","Första Krönikeboken","1 Krön"],
    [14,"FSB/14.html","Andra Krönikeboken","2 Krön"],
    [15,"FSB/15.html","Esra","Esra"],
    [16,"FSB/16.html","Nehemja","Neh"],
    [17,"FSB/17.html","Ester","Ester"],
    [18,"FSB/18.html","Job","Job"],
    [19,"FSB/19.html","Psaltaren","Ps"],
    [20,"FSB/20.html","Ordspråksboken","Ords"],
    [21,"FSB/21.html","Predikaren","Pred"],
    [22,"FSB/22.html","Höga Visan","Höga V"],
    [23,"FSB/23.html","Jesaja","Jes"],
    [24,"FSB/24.html","Jeremia","Jer"],
    [25,"FSB/25.html","Klagovisorna","Klag"],
    [26,"FSB/26.html","Hesekiel","Hes"],
    [27,"FSB/27.html","Daniel","Dan"],
    [28,"FSB/28.html","Hosea","Hos"],
    [29,"FSB/29.html","Joel","Joel"],
    [30,"FSB/30.html","Amos","Amos"],
    [31,"FSB/31.html","Obadja","Ob"],
    [32,"FSB/32.html","Jona","Jona"],
    [33,"FSB/33.html","Mika","Mika"],
    [34,"FSB/34.html","Nahum","Nah"],
    [35,"FSB/35.html","Habackuk","Hab"],
    [36,"FSB/36.html","Sefanja","Sef"],
    [37,"FSB/37.html","Haggai","Hagg"],
    [38,"FSB/38.html","Sakarja","Sak"],
    [39,"FSB/39.html","Malaki","Mal"]
]

var nt = [
    [40,"FSB/40.html","Matteusevangeliet","Matt"],
    [41,"FSB/41.html","Markusevangeliet","Mark"],
    [42,"FSB/42.html","Lukasevangeliet","Luk"],
    [43,"FSB/43.html","Johannesevangeliet","Joh"],
    [44,"FSB/44.html","Apostlagärningarna","Apg"],
    [45,"FSB/45.html","Romarbrevet","Rom"],
    [46,"FSB/46.html","Första Korintierbrevet","1 Kor"],
    [47,"FSB/47.html","Andra Korintierbrevet","2 Kor"],
    [48,"FSB/48.html","Galaterbrevet","Gal"],
    [49,"FSB/49.html","Efesierbrevet","Ef"],
    [50,"FSB/50.html","Filipperbrevet","Fil"],
    [51,"FSB/51.html","Kolosserbrevet","Kol"],
    [52,"FSB/52.html","Första Tessalonikerbrevet","1 Tess"],
    [53,"FSB/53.html","Andra Tessalonikerbrevet","2 Tess"],
    [54,"FSB/54.html","Första Timoteusbrevet","1 Tim"],
    [55,"FSB/55.html","Andra Timoteusbrevet","2 Tim"],
    [56,"FSB/56.html","Brevet till Titus","Tit"],
    [57,"FSB/57.html","Brevet till Filemom","Filem"],
    [58,"FSB/58.html","Hebreerbrevet","Hebr"],
    [59,"FSB/59.html","Jakobs brev","Jak"],
    [60,"FSB/60.html","Första Petrusbrevet","1 Petr"],
    [61,"FSB/61.html","Andra Petrusbrevet","2 Petr"],
    [62,"FSB/62.html","Första Johannesbrevet","1 Joh"],
    [63,"FSB/63.html","Andra Johannesbrevet","2 Joh"],
    [64,"FSB/64.html","Tredje Johannesbrevet","3 Joh"],
    [65,"FSB/65.html","Judas brev","Jud"],
    [66,"FSB/66.html","Uppenbarelseboken","Upp"]
]
